// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { existsSync } from "fs";
import { resolve } from "path";
import { defineConfig, env } from "prisma/config";

// Load environment files in Next.js order (same as seed script)
// This ensures DIRECT_URL is loaded from the correct environment file
const isDev = process.env.NODE_ENV !== "production";

// 1. Base .env (contains AUTH_SECRET and shared config)
const envPath = resolve(process.cwd(), ".env");
if (existsSync(envPath)) {
  config({ path: envPath });
}

// 2. Environment-specific file (.env.development or .env.production)
const envSpecificPath = resolve(
  process.cwd(),
  isDev ? ".env.development" : ".env.production"
);
if (existsSync(envSpecificPath)) {
  config({ path: envSpecificPath, override: true });
}

// 3. .env.local (local overrides, highest priority)
const envLocalPath = resolve(process.cwd(), ".env.local");
if (existsSync(envLocalPath)) {
  config({ path: envLocalPath, override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // IMPORTANT: migrations should use a DIRECT connection string
    // This will be loaded from .env.development (local) or .env.production (remote)
    url: env("DIRECT_URL"),
  },
});
