// ⚠️ SERVER-ONLY: This file uses prisma (database client)
// Do not import this in client components! Only use in API routes, server components, or "use server" functions.

import { prisma } from "./prisma";
import { profileElementFields } from "./profile-element";

// Standard fields to select when fetching a user profile
export const personalProfileFields = {
	id: true,
	handle: true,
	email: true,
	firstName: true,
	middleName: true,
	lastName: true,
	displayName: true,
	headline: true,
	bio: true,
	interests: true,
	location: true,
	visibility: true,
	aboutContent: true,
	avatarImageId: true,
	avatarImage: { select: { url: true } },
	elements: { select: profileElementFields, where: { visible: true }, orderBy: { sortOrder: "asc" as const } },
} as const;

// Public fields (excludes sensitive data like email, but includes ID for messaging)
export const publicUserFields = {
	id: true,
	handle: true,
	firstName: true,
	middleName: true,
	lastName: true,
	displayName: true,
	headline: true,
	bio: true,
	interests: true,
	location: true,
	visibility: true,
	aboutContent: true,
	avatarImageId: true,
	avatarImage: { select: { url: true } },
	elements: { select: profileElementFields, where: { visible: true }, orderBy: { sortOrder: "asc" as const } },
} as const;

// Attribution-only fields for embedding a user on OTHER content (post/event author,
// message participant). Deliberately excludes sensitive profile fields
// (bio/location/interests/aboutContent/email) so a PRIVATE user's details never ride
// along on their public content. The full profile is fetched only by the gated profile
// page via publicUserFields. Enforced by the embed-selector test guard.
export const publicUserEmbedFields = {
	id: true,
	handle: true,
	firstName: true,
	lastName: true,
	displayName: true,
	avatarImageId: true,
	avatarImage: { select: { url: true } },
} as const;

// Fetch a user by ID (for authenticated user's own profile)
export async function getUserById(id: string) {
	return prisma.user.findUnique({
		where: { id },
		select: personalProfileFields,
	});
}

// Fetch a user by handle (formerly username; field renamed in PR 2).
// Uses findFirst with mode: 'insensitive' so lookups are case-insensitive,
// though stored handles are always lowercase per the PR 2 normalization rule
// (so the case-insensitive match is mostly belt-and-suspenders).
export async function getUserByHandle(handle: string) {
	return prisma.user.findFirst({
		where: { handle: { equals: handle, mode: "insensitive" } },
		select: publicUserFields,
	});
}

// Update a user's profile data
export async function updateUserProfile(
	userId: string,
	data: {
		firstName?: string;
		middleName?: string;
		lastName?: string;
		displayName?: string;
		headline?: string;
		bio?: string;
		interests?: string[];
		location?: string;
		visibility?: import("@prisma/client").Visibility;
		avatarImageId?: string | null;
		aboutContent?: string | null;
	},
	tx?: Parameters<Parameters<typeof prisma.$transaction>[0]>[0],
) {
	// Build update data object with only explicitly provided fields
	// This prevents accidentally overwriting fields with undefined
	const updateData: {
		firstName?: string;
		middleName?: string;
		lastName?: string;
		displayName?: string;
		headline?: string;
		bio?: string;
		interests?: string[];
		location?: string;
		visibility?: import("@prisma/client").Visibility;
		avatarImageId?: string | null;
		aboutContent?: string | null;
	} = {};

	if (data.firstName !== undefined) updateData.firstName = data.firstName;
	if (data.middleName !== undefined) updateData.middleName = data.middleName;
	if (data.lastName !== undefined) updateData.lastName = data.lastName;
	if (data.displayName !== undefined) updateData.displayName = data.displayName;
	if (data.headline !== undefined) updateData.headline = data.headline;
	if (data.bio !== undefined) updateData.bio = data.bio;
	if (data.interests !== undefined) updateData.interests = data.interests;
	if (data.location !== undefined) updateData.location = data.location;
	if (data.visibility !== undefined) updateData.visibility = data.visibility;
	if (data.avatarImageId !== undefined) updateData.avatarImageId = data.avatarImageId;
	if (data.aboutContent !== undefined) updateData.aboutContent = data.aboutContent;

	return ((tx ?? prisma) as typeof prisma).user.update({
		where: { id: userId },
		data: updateData,
		select: personalProfileFields,
	});
}

/**
 * Create a new user (with companion Handle row).
 *
 * User IDs are auto-generated by Prisma via `@default(cuid())` in schema.prisma.
 * The Handle row is created atomically via Prisma's nested-write syntax —
 * single SQL transaction at the driver layer, satisfying PR 2's invariant
 * that User and Handle either both exist or neither does.
 *
 * Caller is responsible for:
 *   - Lowercasing `handle` (per PR 2 normalization rule).
 *   - Running `validateHandle` + `isReservedHandle` + `isHandleTaken` first.
 *
 * If a concurrent registration claims the handle between the pre-check and
 * this insert, the unique constraint on `handles.handle` will throw a
 * Prisma `P2002` error which the caller surfaces as "handle already taken."
 */
export async function createUser(data: {
	email: string;
	handle: string;
	passwordHash: string;
	firstName?: string;
	middleName?: string;
	lastName?: string;
	displayName?: string;
}): Promise<{ userId: string }> {
	const names = [data.firstName, data.lastName].filter(Boolean).join(" ");
	const displayName = data.displayName ?? (names || null);

	const user = await prisma.user.create({
		data: {
			email: data.email,
			handle: data.handle,
			passwordHash: data.passwordHash,
			firstName: data.firstName ?? null,
			middleName: data.middleName ?? null,
			lastName: data.lastName ?? null,
			displayName,
			handleRecord: { create: { handle: data.handle } },
		},
		select: { id: true },
	});
	return { userId: user.id };
}

